# config.py

HORIZONTAL_COLS = [
    "Ampenan", "Cakranegara", "Majeluk", "Selaparang", "Batu Layar", "Buwun Mas",
    "Banter Gerung / Banyu Urip", "Gerung", "Gunung Sari", "Labuapi", "Lembar",
    "Narmada", "Pelangan", "Rumak", "Sekotong/Cendimanik", "Sigerongan",
    "Stasiun Klimatologi Kediri", "Bayan", "BBI Santong", "Gangga", "Pemenang",
    "Pemenang Timur", "Sambik Bangkol", "Senaru", "Tanjung", "Batukliang Utara",
    "Batu Nyala/lajut", "Darek", "Janapria", "Kopang", "Mantang/Batukliang",
    "Mertak", "Mujur", "Mujur 2", "Praya /Aikmual", "Praya Barat /Penujak",
    "Pringgarata", "Pujut", "Puyung /Jonggat", "Selong Belanak", "STAMET BIL",
    "Aikmel", "Jerowaru / Sepapan", "karang baru timur/Wanasaba", "Keruak",
    "Kokok Putih Sembalun", "Kotaraja /montong gading", "Labuhan Haji",
    "Labuhan Pandan", "Lenek Duren", "Masbagik", "Montong Baan / Sikur",
    "Perigi", "Pringgabaya", "Pringgasela", "Rarang Selatan",
    "Rensing Sakra Barat", "Sambelia", "Sembalun",
    "Sukamulia /Dasan Lekong", "Swela", "Terara", "Brang Ene", "Brang rea",
    "Maluk", "Tano", "Tapir /Seteluk", "Jereweh", "Taliwang", "Sekongkang",
    "Alas", "Alas Barat", "Batulanteh / Semongkat", "Buer", "Diperta SBW",
    "Empang", "Lab. Badas", "Lape", "Lenangguar", "Lunyuk (Lunyuk Ode)",
    "Moyo Hilir", "Moyo Hulu", "Orong Telu", "Plampang", "Rhee",
    "Sebewe Moyo Utara", "Stasiun Meteorologi Sumbawa", "Sukadamai/Labangka",
    "Tarano", "Utan", "Dompu", "Huu", "Kilo", "Manggalewa", "Pajo",
    "Pekat/Calabai", "Saneo Woja", "Bolo", "Donggo (Oo)", "Lambu", "Madapangga",
    "Madapangga 2", "Monta", "Palibelo Panda", "Palibelo (Teke)", "Sanggar",
    "Sape", "Sape2", "Soromandi", "Stamet Bima", "Wawo", "Wera", "Woha",
    "Asakota", "Kolo", "Raba", "Rasanae Timur", "Kempo (Dompu)",
    "Tambora (Bima)", "Unter Iwes (Sumbawa)", "Donggo Ndano (Bima)",
    "Langgudu Doro Oo (Bima)", "Belo (Bima)", "Parado (Bima)",
    "Lambitu (Bima)", "Kateng (lombok Tengah)",
    "Pandan wangi (Lotim)", "Selong (Lotim)"
]

NAME_MAP = {
    "Batulayar": "Batu Layar",
    "Banyu Urip/Banter": "Banter Gerung / Banyu Urip",
    "Sekotong": "Sekotong/Cendimanik",
    "Staklim Lobar": "Stasiun Klimatologi Kediri",
    "Stamet BIL": "STAMET BIL",
    "Praya": "Praya /Aikmual",
    "Puyung": "Puyung /Jonggat",
    "Mantang": "Mantang/Batukliang",
    "Batu Nyala": "Batu Nyala/lajut",
    "Mujur2/Bilelando": "Mujur 2",
    "Kr Baru Timur/Wanasaba": "karang baru timur/Wanasaba",
    "Kotaraja/Montong Gading": "Kotaraja /montong gading",
    "Jerowaru/Sepapan": "Jerowaru / Sepapan",
    "Kokok Putih/Sembalun": "Kokok Putih Sembalun",
    "Pandan Wangi": "Pandan wangi (Lotim)",
    "Selong": "Selong (Lotim)",
    "Semongkat": "Batulanteh / Semongkat",
    "Diperta Sumbawa": "Diperta SBW",
    "Sebewe/Moyo Utara": "Sebewe Moyo Utara",
    "Stamet Sumbawa": "Stasiun Meteorologi Sumbawa",
    "Unter Iwes": "Unter Iwes (Sumbawa)",
    "Lunyuk": "Lunyuk (Lunyuk Ode)",
    "Kempo": "Kempo (Dompu)",
    "Tambora": "Tambora (Bima)",
    "Donggo2/Ndano": "Donggo Ndano (Bima)",
    "Doro O'o": "Langgudu Doro Oo (Bima)",
    "Belo": "Belo (Bima)",
    "Parado": "Parado (Bima)",
    "Lambitu": "Lambitu (Bima)",
    "Palibelo Teke": "Palibelo (Teke)",
    "Sape 2": "Sape2",
    "Asakota/Jatiwangi": "Asakota",
    "Asakota/Kolo": "Kolo",
    "Santong": "BBI Santong",
    "Moyo hilir": "Moyo Hilir",
    "Moyo hulu": "Moyo Hulu",
    "Brang Rea": "Brang rea",
    "Donggo": "Donggo (Oo)",
    "Penujak": "Praya Barat /Penujak",
    "Sikur": "Montong Baan / Sikur",
    "Sukamulia/Dasan Lekong": "Sukamulia /Dasan Lekong",
    "Tapir/Seteluk": "Tapir /Seteluk",
    "Kateng": "Kateng (lombok Tengah)",
}